// <auto-generated />
using System;
using HD_Support_API.Components;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HD_Support_API.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240405150124_tokenEmail2")]
    partial class tokenEmail2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("HD_Support_API.Models.Conversa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("clienteid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("criptografia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("data_conclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("data_inicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("funcionariosid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tipoconversa")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Conversa");
                });

            modelBuilder.Entity("HD_Support_API.Models.Emprestimos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipamentosid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("equipamentosid");

                    b.HasIndex("usuarioid");

                    b.ToTable("Emprestimo");
                });

            modelBuilder.Entity("HD_Support_API.Models.equipamentos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dtemeprestimofinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dtemeprestimoinicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadSet")
                        .HasColumnType("TEXT");

                    b.Property<int?>("idpatrimonio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Processador")
                        .HasColumnType("TEXT");

                    b.Property<string>("SistemaOperacional")
                        .HasColumnType("TEXT");

                    b.Property<string>("profissional_hd")
                        .HasColumnType("TEXT");

                    b.Property<int>("statusEquipamento")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Equipamento");
                });

            modelBuilder.Entity("HD_Support_API.Models.Mensagens", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("conversaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data_envio")
                        .HasColumnType("TEXT");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("HD_Support_API.Models.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataHoraGeracaoToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusConversa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HD_Support_API.Models.Conversa", b =>
                {
                    b.HasOne("HD_Support_API.Models.Usuarios", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HD_Support_API.Models.Usuarios", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("HD_Support_API.Models.Emprestimos", b =>
                {
                    b.HasOne("HD_Support_API.Models.equipamentos", "Equipamento")
                        .WithMany()
                        .HasForeignKey("equipamentosid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HD_Support_API.Models.Usuarios", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("HD_Support_API.Models.Mensagens", b =>
                {
                    b.HasOne("HD_Support_API.Models.Usuarios", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
